# Generated by Django 4.2.23 on 2025-07-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_exo_1', '0003_alter_facture_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='adresse_client',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='email_client',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='nom_client',
        ),
    ]
